<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Operations;

use Bannerify\Bannerify\Utils\SpeakeasyMetadata;
class GetV1InfoRequest
{
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=apiKey')]
    public string $apiKey;

    public function __construct()
    {
        $this->apiKey = '';
    }
}