<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Operations;



enum QueryParamFormat: string
{
    case Png = 'png';
    case Svg = 'svg';
}
