<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Components;


/** A machine readable error code. */
enum Code: string
{
    case Unauthorized = 'UNAUTHORIZED';
}
