<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Components;


class ErrConflictError
{
    /**
     * A machine readable error code.
     *
     * @var \Bannerify\Bannerify\Models\Components\ErrConflictCode $code
     */
    #[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('enum<Bannerify\Bannerify\Models\Components\ErrConflictCode>')]
    public ErrConflictCode $code;

    /**
     * A link to our documentation with more details about this error code
     *
     * @var string $docs
     */
    #[\JMS\Serializer\Annotation\SerializedName('docs')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $docs;

    /**
     * A human readable explanation of what went wrong
     *
     * @var string $message
     */
    #[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;

    /**
     * Please always include the requestId in your error report
     *
     * @var string $requestId
     */
    #[\JMS\Serializer\Annotation\SerializedName('requestId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $requestId;

    public function __construct()
    {
        $this->code = \Bannerify\Bannerify\Models\Components\ErrConflictCode::Conflict;
        $this->docs = '';
        $this->message = '';
        $this->requestId = '';
    }
}