<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Components;


class ErrForbidden
{
    #[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('Bannerify\Bannerify\Models\Components\ErrForbiddenError')]
    public ErrForbiddenError $error;

    public function __construct()
    {
        $this->error = new \Bannerify\Bannerify\Models\Components\ErrForbiddenError();
    }
}