<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Components;


/** Modification - A modification (aka override) to apply to the layer in image */
class Modification
{
    /**
     * The layer name of the modification
     *
     * @var string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;

    /**
     * The color for the modification
     *
     * @var ?string $color
     */
    #[\JMS\Serializer\Annotation\SerializedName('color')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $color = null;

    /**
     * The source image for the modification
     *
     * @var ?string $src
     */
    #[\JMS\Serializer\Annotation\SerializedName('src')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $src = null;

    /**
     * You can modify the text layer with this field
     *
     * @var ?string $text
     */
    #[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $text = null;

    /**
     * Modify the barcode layer content with this field
     *
     * @var ?string $barcode
     */
    #[\JMS\Serializer\Annotation\SerializedName('barcode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $barcode = null;

    /**
     * Modify the qrcode layer content with this field
     *
     * @var ?string $qrcode
     */
    #[\JMS\Serializer\Annotation\SerializedName('qrcode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $qrcode = null;

    /**
     * Update chart layer's data, follow chart.js data structure
     *
     * @var ?array<string, mixed> $chart
     */
    #[\JMS\Serializer\Annotation\SerializedName('chart')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $chart = null;

    /**
     * Set the visibility of the field
     *
     * @var ?bool $visible
     */
    #[\JMS\Serializer\Annotation\SerializedName('visible')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $visible = null;

    /**
     * Star value
     *
     * @var ?float $star
     */
    #[\JMS\Serializer\Annotation\SerializedName('star')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $star = null;

    public function __construct()
    {
        $this->name = '';
        $this->color = null;
        $this->src = null;
        $this->text = null;
        $this->barcode = null;
        $this->qrcode = null;
        $this->chart = null;
        $this->visible = null;
        $this->star = null;
    }
}