<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bannerify\Bannerify\Models\Components;

use Bannerify\Bannerify\Utils\SpeakeasyMetadata;
class Security
{
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=query,name=apiKey')]
    public string $bearerAuth;

    public function __construct()
    {
        $this->bearerAuth = '';
    }
}